// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF0XDOxjHzyIZt1k9hJwxWpstQEQiCnqg',
    appId: '1:76921457877:web:647da3f02220817276665c',
    messagingSenderId: '76921457877',
    projectId: 'testing-d2133',
    authDomain: 'testing-d2133.firebaseapp.com',
    storageBucket: 'testing-d2133.appspot.com',
    measurementId: 'G-DRK5FMSL83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKQM_ICCPpP8qfyEL21OQVdSr_bGk-AUU',
    appId: '1:76921457877:android:8d816b36a9e50cf276665c',
    messagingSenderId: '76921457877',
    projectId: 'testing-d2133',
    storageBucket: 'testing-d2133.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOqD7oIM6v5l_ngOvx0R6xfFJb-uirxvo',
    appId: '1:76921457877:ios:1c360d3a2028482576665c',
    messagingSenderId: '76921457877',
    projectId: 'testing-d2133',
    storageBucket: 'testing-d2133.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOqD7oIM6v5l_ngOvx0R6xfFJb-uirxvo',
    appId: '1:76921457877:ios:1c360d3a2028482576665c',
    messagingSenderId: '76921457877',
    projectId: 'testing-d2133',
    storageBucket: 'testing-d2133.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );
}
